### ISSUE TITLE
esp-tls-mbedtls: No server verification option set in esp_tls_cfg_t structure. Check esp_tls API reference

### ISSUE THREAD

**Issue by zonmen** [zonmen/esp32#1]
I use esp32, idf sdk and when tried to make simple http request I saw that problem. I coludn't do this, because don't use any certification. After an hour I was able to fix it. I am new on this platform and programming mcu, so it's guide just for those who like me, don't understand most of idf and ide config and just started in it

**Comment by zonmen** [comment]
**problem is**: As I understood, idf updated and now when you use Internet requests you need to server cert verification
heading ESP-TLS in https://newreleases.io/project/github/espressif/esp-idf/release/v4.3-beta1   

**solve**: In project folder(root folder) we need to change "sdkconfig" file. In menu choose Component config->ESP LTS-> (enable these options) "Allow potentially insecure options" and then "Skip server verification by default". I did it in my ide(eclipse).
or way for die-hard(using menuconfig in terminal, on my example):

**1. Go to root derictory esp-idf in terminal**

~/programs/eclipse_work-space/my_libs/esp-idf-v4.3

**2. Run file "install.sh"**

//I use ubuntu, so first of all, I did this file executable

chmod +x install.sh

//and run

./install.sh

**3.Then run "export.sh"**

//this file we need to run like source(?), so I just ran this 


. ./export.sh

**4.Go to folder /tools (into the root esp-idf/)**

cd tools

**5.Make "idf.py" executable(this is file in tools folder)**

cd tools

//one more time in my case

chmod +x idf.py

**6. Go to your current project and do "idf.py menuconfig"**

cd ~/programs/eclipse_work-space/whole_project

idf.py menuconfig

//it opens a menu to config your project

**7. Navigation in menu**

Component config->ESP-TLS->(enable these) "Allow potentially insecure options" and THEN "Skip server certificate verification by default (WARNING ...)" 

**8. Save and quit**

Work is done!


Links:
1) answers(but I couldn't find this config file):
https://www.esp32.com/viewtopic.php?t=19200
https://github.com/espressif/arduino-esp32/issues/5176
2) Generall information about esp idf configuration:
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#component-config

**Comment by zonmen** [comment]
OK, i find my problem. 
Just add these lines to your sdkconfig.defaults file:
CONFIG_ESP_TLS_INSECURE=y
CONFIG_ESP_TLS_SKIP_SERVER_CERT_VERIFY=y

**Comment by wisal-sarez** [comment]
Thanks a lot @zonmen ,
changing sdkconfig file helped me, thanks a lot,

**Comment by Chiendlb8630** [comment]
OMG, many thanks to u!!!! That really solved my problem
